# Generated by Django 4.0 on 2024-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usurio',
            field=models.CharField(default='usuario_comun', max_length=50),
        ),
    ]
