# Generated by Django 4.0 on 2024-06-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_tipo_usurio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionInsegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_inseguras', to='backend.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='ActoInseguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actos_inseguros', to='backend.puesto')),
            ],
        ),
    ]
