# Generated by Django 4.0 on 2024-07-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_puesto_condicioninsegura_actoinseguro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
