# Generated by Django 4.0 on 2024-07-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_reportante', models.CharField(max_length=20, verbose_name='N° DNI DEL REPORTANTE')),
                ('apellidos_nombres', models.CharField(max_length=100, verbose_name='APELLIDOS Y NOMBRES')),
                ('puesto_trabajo', models.CharField(max_length=50, verbose_name='PUESTO DE TRABAJO')),
                ('area', models.CharField(max_length=50, verbose_name='ÁREA')),
                ('tipo_evaluacion', models.CharField(max_length=50, verbose_name='TIPO DE EVALUACIÓN')),
                ('puesto_a_evaluar', models.CharField(max_length=50, verbose_name='PUESTO A EVALUAR')),
                ('motivo_no_cumple', models.TextField(verbose_name='MOTIVO POR QUÉ NO CUMPLE')),
                ('dni_persona_reportada_acto', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° DNI DE LA PERSONA REPORTADA POR ACTO')),
                ('imagen_evaluacion', models.ImageField(blank=True, null=True, upload_to='evaluaciones/', verbose_name='Imagen de Evaluación')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='NormaNoNego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=200, verbose_name='Norma')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('evaluacion_condiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normas_no_nego', to='backend.evaluaciones')),
            ],
        ),
    ]
