# Generated by Django 4.0 on 2024-07-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_evaluaciones_normanonego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='motivo_no_cumple',
            field=models.CharField(max_length=50, verbose_name='MOTIVO POR QUÉ NO CUMPLE'),
        ),
    ]
