# Generated by Django 4.0 on 2024-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_evaluaciones_motivo_no_cumple'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='sin correo', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
