# Generated by Django 4.2.13 on 2024-07-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicioninsegura',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='normanonego',
            name='evaluacion_condiciones',
        ),
        migrations.DeleteModel(
            name='ActoInseguro',
        ),
        migrations.DeleteModel(
            name='CondicionInsegura',
        ),
        migrations.DeleteModel(
            name='Evaluaciones',
        ),
        migrations.DeleteModel(
            name='NormaNoNego',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
