# Generated by Django 4.2.13 on 2024-07-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_condicioninsegura_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioDePesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarcacion', models.CharField(max_length=255)),
                ('flota', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('numero_alcance', models.IntegerField()),
                ('zona_pesca', models.CharField(max_length=255)),
                ('estrato', models.CharField(max_length=255)),
                ('rango_profundidad_inicial', models.IntegerField()),
                ('rango_profundidad_final', models.IntegerField()),
                ('tiempo_efectivo', models.TimeField()),
                ('rango_talla_inicial', models.IntegerField()),
                ('rango_talla_final', models.IntegerField()),
                ('moda', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ar', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
