# Generated by Django 4.2.13 on 2024-07-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_diariodepesca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usurio',
            field=models.CharField(max_length=50),
        ),
    ]
