# Generated by Django 4.2.8 on 2024-07-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_embarcaciones_especies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diariodepesca',
            old_name='flota',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='diariodepesca',
            old_name='rango_profundidad_final',
            new_name='profundidad',
        ),
        migrations.RemoveField(
            model_name='diariodepesca',
            name='rango_profundidad_inicial',
        ),
    ]
