# Generated by Django 4.2.8 on 2024-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_flota_diariodepesca_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodepesca',
            name='embarcacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diariodepesca',
            name='especie',
            field=models.IntegerField(),
        ),
    ]
