# Generated by Django 4.2.8 on 2024-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_mecanismosi_tarifascostos_viveres_zonapesca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifascostos',
            name='tarifa',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
