# Generated by Django 4.2.8 on 2024-07-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_tipodescripcion_costogalon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoGalonAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoGalonB_05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoGalonHielo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoTipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoTripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_basico', models.DecimalField(decimal_places=2, max_digits=9)),
                ('participacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_participacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('aporte_REP', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gratificacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=9)),
                ('CTS', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ESSALUD', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SENATI', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SCTR_SAL', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SCTR_PEN', models.DecimalField(decimal_places=2, max_digits=9)),
                ('poliza_seguro', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_CT', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FlotaDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_faena', models.DurationField()),
                ('kilos_declarados', models.DecimalField(decimal_places=2, max_digits=9)),
                ('merluza', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('bereche', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('volador', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('merluza_descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('otro', models.CharField(blank=True, max_length=255, null=True)),
                ('kilo_otro', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('toneladas_procesadas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('toneladas_recibidas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.embarcaciones')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.costotipocambio')),
                ('zona_pesca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.zonapesca')),
            ],
        ),
        migrations.RenameModel(
            old_name='DiarioDePesca',
            new_name='Lances',
        ),
        migrations.AlterField(
            model_name='viveres',
            name='embarcacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.embarcaciones'),
        ),
        migrations.DeleteModel(
            name='CostoGalon',
        ),
        migrations.DeleteModel(
            name='TipoDescripcion',
        ),
    ]
