# Generated by Django 4.2.8 on 2024-07-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_costogalonagua_costogalonb_05_costogalonhielo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lances',
            new_name='DiarioDePesca',
        ),
    ]
