# Generated by Django 4.2.8 on 2024-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_lances_diariodepesca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoGasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarcacion', models.IntegerField()),
                ('consumo_gasolina', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
