# Generated by Django 4.2.8 on 2024-07-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_flotadp_consumo_agua_flotadp_consumo_gasolina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanismosi',
            old_name='costo_día',
            new_name='costo_dia',
        ),
    ]
