# Generated by Django 4.2.8 on 2024-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_rename_costo_día_mecanismosi_costo_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='total_tripulación',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
