# Generated by Django 4.2.8 on 2024-07-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_flotadp_total_tripulación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flotadp',
            old_name='días_inspeccion',
            new_name='dias_inspeccion',
        ),
        migrations.RenameField(
            model_name='flotadp',
            old_name='total_tripulación',
            new_name='total_tripulacion',
        ),
    ]
