# Generated by Django 4.2.8 on 2024-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_días_inspeccion_flotadp_dias_inspeccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flotadp',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
