# Generated by Django 4.2.8 on 2024-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_flotadp_tipo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcaciones',
            name='costo_zarpe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
