# Generated by Django 4.2.8 on 2024-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_embarcaciones_costo_zarpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerechoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
