# Generated by Django 4.2.8 on 2024-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_derechopesca'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='csot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
