# Generated by Django 4.2.8 on 2024-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_flotadp_csot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flotadp',
            name='horas_faena',
            field=models.CharField(max_length=255),
        ),
    ]
