# Generated by Django 4.2.8 on 2024-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_flotadp_horas_faena'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcaciones',
            name='fecha',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
