# Generated by Django 4.2.8 on 2024-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_embarcaciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcaciones',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
